### ISSUE TITLE
error headerName 

### ISSUE THREAD

**Issue by sam9010** [rinku-k/rn-checkbox-list#10]
when headerName  active
and i checked or not checked my list remove item

**Comment by rinku-k** [comment]
Please provide more details.
1. Which version are you facing the issue with?
2. Is the issue reproducible in the latest release?

**Comment by sam9010** [comment]
i use last version with 0.60 react native
 try to get a film from my bog and upload

**Comment by sam9010** [comment]
i use last version with 0.60 react native
try to get a film from my bog and upload
i wrong on touch in close button
