### ISSUE TITLE
requireNativeComponent "androidCheckbox" was not found in the UI manager

### ISSUE THREAD

**Issue by tonydatw** [rinku-k/rn-checkbox-list#18]
I'm getting this error after installing the library with the yarn command line `yarn add rn-checkbox-list` and import it. What am i missing?
![Screenshot_1631987184](https://user-images.githubusercontent.com/54851722/133897884-9e5e2753-9e3a-491f-a253-33c171e19e63.png)

**Comment by sameer-j** [comment]
Looks like dependency (@react-native-community/checkbox) for this package is not getting installed automatically when added via yarn.

@tonydatw add the package via `yarn add @react-native-community/checkbox` and try again. It should work.

**Comment by sam9010** [comment]
Hi
I have same error, install  @react-native-community/checkbox but has error
