### ISSUE TITLE
selected item issue

### ISSUE THREAD

**Issue by Khairala** [rinku-k/rn-checkbox-list#36]
how to empty the selected item list after going back from the screen that have the CheckboxList ?

because every time i go back and empty the selected list it doesn't change i guess it's a problem in the onchange attribute because every time i console.log inside it like this 
        onChange={({ ids, items }) => {console.log(items}} 
the items remains the same !
can u help me plz !

**Comment by sameer-j** [comment]
Your component may not be unmounting or the data fed to the checklist is not reset. This does not look like an issue with the rn-checkbox-list. Please share your code to help better.
