### ISSUE TITLE
not visible on ios

### ISSUE THREAD

**Issue by rubimbura** [rinku-k/rn-checkbox-list#6]
tried this library and the boxes are not visible on ios. any help?

**Comment by rinku-k** [comment]
Hi, the library is supporting android only now.
I will try adding setup for iOS and code for the same.

Please share the screenshot and provide detailed description - 

1.  iOS version you tested
2. When you select, does the element gets selected (is the tick shown)

**Comment by rinku-k** [comment]
I have released [v0.3.0](https://github.com/rinku-k/rn-checkbox-list/releases/tag/0.3.0)
Please check and let me know if it works for you.

PS: I could not test in iOS as I have formatted my MacOS😞 I should be able to test and close this ticket after 24hours.

**Comment by Faiyyazauxy** [comment]
My screen becomes black on iOS simulator. Haven't checked in real device though

**Comment by rinku-k** [comment]
Hey, I have just tested this in the iOS simulator. It works fine for version0.3.1.
Please upgrade to latest version.
