### ISSUE TITLE
Elements in the list disappear

### ISSUE THREAD

**Issue by Anthares101** [rinku-k/rn-checkbox-list#9]
I dont know if this is a known problem but in android after clicking on the select all option, if you try to uncheck an element it will get removed from the list.

**Comment by rinku-k** [comment]
I am not sure if I understood your question correctly, but are you pointing to 
` onChange={({ ids, items }) => console.log('My updated list :: ', ids)} `
or the UI?

**Comment by Anthares101** [comment]
The UI, the data itself is still there

**Comment by rinku-k** [comment]
Yeah, I could see the issue. Let me fix it quickly.

**Comment by rinku-k** [comment]
Have published new npm version `v0.4.0` with the fix.
Thank you for reporting the issue :)

**Comment by Anthares101** [comment]
Nice! Thanks for the fast response. Everything is working perfect now so i will close this 😄
